# Generated by Django 5.2.16 on 2026-07-28 16:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='beer/')),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ichimlik (Beer)',
                'verbose_name_plural': 'Ichimliklar (Beer)',
            },
        ),
        migrations.CreateModel(
            name='BreakfastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='breakfast_categories/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Breakfast kategoriyasi',
                'verbose_name_plural': 'Breakfast kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Masalan: breakfast, special, desert, dinner', unique=True)),
            ],
            options={
                'verbose_name': 'Taom kategoriyasi',
                'verbose_name_plural': 'Taom kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='SiteAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('short_text', models.TextField(help_text='Bosh sahifada darhol koringan qisqa matn')),
                ('full_text', models.TextField(help_text="'Ko'proq' bosilganda ochiladigan toliq matn")),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Us bolimi',
                'verbose_name_plural': 'About Us bolimi',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], unique=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Belgilansa, shu kun umuman ishlamaydi')),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqtlari',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='BreakfastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='breakfast_items/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='project.breakfastcategory')),
            ],
            options={
                'verbose_name': 'Breakfast taomi',
                'verbose_name_plural': 'Breakfast taomlari',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='menu/')),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='menu_items', to='project.category')),
            ],
            options={
                'verbose_name': 'Taom (Pricing)',
                'verbose_name_plural': 'Taomlar (Pricing)',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism Familya')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('reservation_date', models.DateField(verbose_name='Bron sanasi')),
                ('reservation_time', models.TimeField(verbose_name='Bron vaqti')),
                ('guest_count', models.PositiveSmallIntegerField(help_text='1 ta stol uchun maksimum 10 kishi', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Kishilar soni')),
                ('comment', models.TextField(blank=True, verbose_name='Sharh')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beer_items', models.ManyToManyField(blank=True, related_name='reservations', to='project.beeritem')),
                ('breakfast_items', models.ManyToManyField(blank=True, related_name='reservations', to='project.breakfastitem')),
                ('menu_items', models.ManyToManyField(blank=True, related_name='reservations', to='project.menuitem')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
